export const Type = {
    SET_ERROR: 'SET_ERROR',
    SET_SERVER_ERROR: 'SET_SERVER_ERROR',    
    CLEAR_ERROR: 'CLEAR_ERROR',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    LOGOUT_CURRENT_USER: 'LOGOUT_CURRENT_USER',
    SET_PRODUCTS: "SET_PRODUCTS",
    GET_PRODUCT: "GET_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    GET_CART: 'GET_CART',
    RESTORE_CART: 'RESTORE_CART',    
    CLEAR_CART: 'CLEAR_CART',    
    REMOVE_ITEM: 'REMOVE_ITEM',
    ORDER_VALIDATION_ERROR: 'ORDER_VALIDATION_ERROR',
    INFO_MESSAGE: 'INFO_MESSAGE'
    
}